language: php

php:
  - 5.6

env:
  global:
    - setup=basic

sudo: false

install:
  - /home/travis/.phpenv/versions/5.6/bin/composer self-update
  - travis_retry composer install --no-interaction --prefer-source;

script: vendor/bin/phpunit
